### ISSUE TITLE
Add BigQuery table description when loading data

### ISSUE THREAD

**Issue by dkapitan** [dkapitan/nimbletl#1]
Use `destination_table_description` in [`bigquery.job.LoadJob`](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.job.LoadJob.html)

**Comment by TxEddy** [comment]
tasks.py will now also load the description of the tables into BigQuery while loading the data

**Comment by TxEddy** [comment]
In [DataProperties](https://opendata.cbs.nl/ODataFeed/odata/82339NED/DataProperties) staat ook een algemene beschrijving onder 'Regioaanduiding' (heeft ID=1). Hierin staat uitgelegd wat een Wijk en Buurt is, handig om dit mee te nemen? Zo ja, is het dan beter om aparte method voor de beschrijving van de tabel te maken?

**Comment by dkapitan** [comment]
@TxEddy lijkt mij inderdaad beter om aparte method voor beschrijvingen van DataProperties te schrijven. Volgens mij kan je in BigQuery ook comments per kolom toevoegen.

**Comment by TxEddy** [comment]
@dkapitan Nieuwe method aangemaakt voor het toevoegen van beschrijving van de tabel. Kennelijk is er een kleine beschrijving (wat nu wordt ingeladen) en grote beschrijving dat een kleine inhoudsopgave heeft, maar kan in principe ook worden ingeladen in BigQuery ipv de kleine beschrijving. Wat heeft de voorkeur?

**Comment by dkapitan** [comment]
@TxEddy 
Ik begrijp niet wat de tweede optie is (met inhoudsopgave). Heb je een URL naar de documentatie en/of een voorbeeld?

**Comment by TxEddy** [comment]
Dit is de kleine beschrijving:
<img width="717" alt="Schermafbeelding 2020-08-06 om 19 43 43" src="https://user-images.githubusercontent.com/19187208/89564922-06a02b00-d81e-11ea-90f2-0ea83a60ea65.png">

Dit is de grote beschrijving:
<img width="719" alt="Schermafbeelding 2020-08-06 om 19 44 56" src="https://user-images.githubusercontent.com/19187208/89564980-20417280-d81e-11ea-9335-613c94257565.png">

**Comment by dkapitan** [comment]
@TxEddy 
Ah, je bedoelt de tekst van CBS. Ik zou graag de lange erin zetten, maar dat past waarschijnlijk niet altijd: maximaal 1.024 karakters in een table.description.

Dus dan liever maar een short description + de URL als mensen meer info over de tabel willen.

**Comment by TxEddy** [comment]
@dkapitan Ooh, maar de huidige bevat al volgens mij al 4985 karakters en bij het testen voor alle tabellen kreeg ik geen error over max characters. Geldt dat limiet niet alleen voor table.name en column description?

**Comment by dkapitan** [comment]
@TxEddy 
In that case: Lange omschrijving van CBS!
